config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  scope "/admin" do
    resources :users
  end
  resources :games
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'games#index'
  post 'games/add_bgg'
  get 'games/new'
end

app/models/game.rb
class Game
  include Mongoid::Document
  resourcify
  field :name, type: String
  field :minimum_players, type: Integer
  field :maximum_players, type: Integer
  field :minimum_playtime, type: Integer
  field :maximum_playtime, type: Integer
  field :typical_playtime, type: Integer
  field :age, type: Integer
  #field :categories, type: Array
  belongs_to :user

  validates_presence_of(:name)
  validates :name, :uniqueness => {:scope=>:user}
  validates_presence_of(:user)
  validates_numericality_of :minimum_players, greater_than: 0
  validates_numericality_of :maximum_players, greater_than_or_equal_to: :minimum_players
  validates_numericality_of :minimum_playtime, greater_than_or_equal_to: 0
  validates_numericality_of :maximum_playtime, greater_than_or_equal_to: :minimum_playtime
  validates_numericality_of :typical_playtime, less_than_or_equal_to: :maximum_playtime, greater_than_or_equal_to: :minimum_playtime, allow_nil: true
  validates_numericality_of :age, greater_than_or_equal_to: 0, allow_nil: true
end

app/controllers/games_controller.rb
require 'open-uri'

class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def search_bgg(name)
    uri = "https://www.boardgamegeek.com/xmlapi/search?search=" + URI.encode(name)
    result = Nokogiri::HTML(open(uri))

  end

  def make_name_hash(xml_doc)
    xml_game_list = xml_doc.xpath("//boardgame")
    game_hash = Hash.new
    xml_game_list.each do |xml_game|
      name_string = xml_game.xpath("name").inner_text + " [" + xml_game.xpath("yearpublished").inner_text + "]"
      id = xml_game.attr("objectid")
      game_hash[name_string] = id
    end

    return game_hash
  end

  def get_bgg_details(id)
    uri = "https://www.boardgamegeek.com/xmlapi/boardgame/" + id
    result = Nokogiri::HTML(open(uri))
  end

  def parse_bgg_details(game_xml)
    params = Hash.new
    string_translation = {"name" => "//name[primary=true]",
                          "minimum_players" => "//minplayers",
                          "maximum_players" => "//maxplayers",
                          "minimum_playtime" => "//minplaytime",
                          "maximum_playtime" => "//maxplaytime",
                          "typical_playtime" => "//playingtime",
                          "age" => "//age"};
    string_translation.each do |para_key, xml_key|
      params[para_key] = game_xml.at_css(xml_key).inner_text
    end
    return params
  end

  def add_bgg_game(id)
    cur_game = get_bgg_details(id)
    cur_game_params = parse_bgg_details(cur_game)
    @game = Game.new(cur_game_params)
    @game.user = current_user.id
    @game.save #Add test for successful save here. Perhaps through counter.
  end

  def add_all_bgg_games(id_array)
    id_array.each do |id|
      add_bgg_game(id)
    end
  end

  def add_bgg
    id_array = params["selector"]["id"]
    add_all_bgg_games(id_array)
    redirect_to games_url
  end

  def filtered_game_list(filter_params)
    @games = @games.where(:age.lte => filter_params["age"]) if (filter_params["age"] != "" && filter_params["age"] != nil)
    @games = @games.where(:maximum_playtime.lte => filter_params["play_time_max"]) if (filter_params["play_time_max"] != "" && filter_params["play_time_max"] != nil)
    @games = @games.where(:minimum_playtime.gte => filter_params["play_time_min"]) if (filter_params["play_time_min"] != "" && filter_params["play_time_min"] != nil)
    @games = @games.where(:minimum_players.lte => filter_params["num_play"]) if (filter_params["num_play"] != "" && filter_params["num_play"] != nil)
    @games = @games.where(:maximum_players.gte => filter_params["num_play"]) if (filter_params["num_play"] != "" && filter_params["num_play"] != nil)
    return @games

  end

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
    @games = @games.where(:user => current_user)
    if params["commit"] == "Filter"
      @games = filtered_game_list(params)
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new

    if params["search"]
      @name = params["search"]["bgg_search"]
      @bgg_xml = search_bgg(@name)
      @bgg_hash = make_name_hash(@bgg_xml)
    end

    render :new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.user = current_user
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    if @game.user == current_user
      updated = @game.update(game_params)
      @notice = "Game was sucessfully updated."
    else
      @notice = "Game not updated since it belongs to another user."
    end
    respond_to do |format|
      if updated
        format.html { redirect_to @game, notice: @notice }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    if @game.user == current_user
      @game.destroy
      @notice = 'Game was successfully destroyed.'
    else
      @notice = 'Game not deleted since it belongs to another user.'
    end
    respond_to do |format|
      format.html { redirect_to games_url, notice: @notice }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      if Game.where(id: params[:id]).exists?
        @game = Game.find(params[:id])
      else
        @game = Game.new
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :minimum_players, :maximum_players, :minimum_playtime, :maximum_playtime, :typical_playtime, :age, :categories)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_bgg_search.html.erb
<h2> Search Board Game Geek </h2>

<%= form_for :search, url: "new", method: "get" do |form| %>
  <div class="field">
    <%= form.text_field :bgg_search %>
  </div>
  <div class="actions">
    <%= form.submit "Search"%>
  </div>
<% end %>

<% if search_results %>
  <%= form_tag("add_bgg", method: "post") do %>
    <div class="field">
      <%= collection_select('selector', 'id', search_results, :last, :first, {:include_hidden => false}, {:multiple => true})  %>


    </div>
    <div class="actions">
      <%= submit_tag "Add" %>
    </div>
  <% end %>


  </div>
<% end %>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :minimum_players %>
    <%= form.number_field :minimum_players %>
  </div>

  <div class="field">
    <%= form.label :maximum_players %>
    <%= form.number_field :maximum_players %>
  </div>

  <div class="field">
    <%= form.label :minimum_playtime %>
    <%= form.number_field :minimum_playtime %>
  </div>

  <div class="field">
    <%= form.label :maximum_playtime %>
    <%= form.number_field :maximum_playtime %>
  </div>

  <div class="field">
    <%= form.label :typical_playtime %>
    <%= form.number_field :typical_playtime %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

<!--  <div class="field">-->
    <%#= form.label :categories %>
    <%#= form.text_field :categories %>
<!--  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <a class="navbar-brand" href="#">Games</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="form-group">
    <%= form_tag(games_url, method: "get", :class => 'form-inline border m-2 d-inline-flex') do %>
      <div class="input-group m-3">

        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1">Number of players: </span>
        </div>
        <%= number_field_tag(:num_play, nil, class: "form-control") %>
      </div>
      <div class="input-group m-3">

        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1">Minimum playtime: </span>
        </div>
        <%= number_field_tag(:play_time_min, nil, class: "form-control") %>
      </div>
      <div class="input-group m-3">

        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1">Maximum playtime: </span>
        </div>
        <%= number_field_tag(:play_time_max, nil, class: "form-control") %>
      </div>
      <div class="input-group m-3">

        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1">Age: </span>
        </div>
        <%= number_field_tag(:age, nil, class: "form-control") %>
      </div>
      <%= submit_tag("Filter", class: "btn btn-primary  m-3") %>
      </div>
    <% end %>
    <div class="border m-1">
      <%= link_to 'New Game', new_game_path, :class => "btn btn-primary m-3" %>
    </div>
    <div class="border m-1">
      <%= link_to 'Log Out', destroy_user_session_path, {:method => 'delete', :class => "btn btn-primary m-3"} %>
    </div>
    <div class="border m-1">
      <%= link_to 'My profile', edit_user_registration_path, {:method => 'get', :class => "btn btn-primary m-3"} %>
    </div>
    <% if can? :manage, User %>
      <%= link_to 'Users', users_path, {:method => 'get', :class => "btn btn-primary m-3"} %>
    <% end %>
    </nav>


<table class="table m-2 table-bordered table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Minimum players</th>
      <th>Maximum players</th>
      <th>Minimum playtime</th>
      <th>Maximum playtime</th>
      <th>Typical playtime</th>
      <th>Age</th>
<!--      <th>Categories</th>-->
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.minimum_players %></td>
        <td><%= game.maximum_players %></td>
        <td><%= game.minimum_playtime %></td>
        <td><%= game.maximum_playtime %></td>
        <td><%= game.typical_playtime %></td>
        <td><%= game.age %></td>
<!--        <td><%#= game.categories %></td>-->
        <td><%= game.user  %></td>
        <td><%= link_to '&#128065;'.html_safe, game %></td>
        <td><%= link_to '&#128221;'.html_safe, edit_game_path(game) %></td>
        <td><%= link_to '&#128465;'.html_safe, game, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/games/new.html.erb
<h1>New Game</h1>

<div>
  <%= render 'form', game: @game %>
</div>
<div>
  <%= render 'bgg_search', search_results: @bgg_hash %>
</div>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Minimum players:</strong>
  <%= @game.minimum_players %>
</p>

<p>
  <strong>Maximum players:</strong>
  <%= @game.maximum_players %>
</p>

<p>
  <strong>Minimum playtime:</strong>
  <%= @game.minimum_playtime %>
</p>

<p>
  <strong>Maximum playtime:</strong>
  <%= @game.maximum_playtime %>
</p>

<p>
  <strong>Typical playtime:</strong>
  <%= @game.typical_playtime %>
</p>

<p>
  <strong>Age:</strong>
  <%= @game.age %>
</p>

<!--<p>-->
<!--  <strong>Categories:</strong>-->
  <%#= @game.categories %>
<!--</p>-->

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>